"""
Answer generator.

Produces the final response with quality controls:
    1. LLM generates answer from retrieved context / diagnostic data
    2. Grounding check scores 0–1 (how well answer is supported by context)
    3. If score < HANDOFF_THRESHOLD → trigger human handoff
    4. Otherwise → return final answer
"""

import re
from dataclasses import dataclass
from typing import Optional

from llm.client import call_llm

HANDOFF_THRESHOLD = 0.25   # word-overlap heuristic — LLM-based scorer in Phase 4

SYSTEM_PROMPT = {
    "th": (
        "คุณคือผู้ช่วย AI ของ Salary Hero สำหรับตอบคำถามด้าน HR และการเงิน\n"
        "กฎเหล็ก:\n"
        "- ใช้เฉพาะข้อมูลที่ปรากฏใน Context ด้านล่างเท่านั้น\n"
        "- ห้ามเพิ่มเติม คาดเดา หรือสร้างข้อมูลใดๆ ที่ไม่มีอยู่ใน Context โดยเด็ดขาด\n"
        "- ห้ามขึ้นต้นคำตอบด้วย 'จากข้อมูล', 'ตามข้อมูล', 'จากบริบท' หรือประโยคอ้างอิง Context ใดๆ ให้ตอบตรงๆ เลย\n"
        "- ห้ามเพิ่มหัวข้อหรือประโยคแนะนำคำถามเพิ่มเติมใดๆ ท้ายคำตอบ เช่น 'คำถามที่เกี่ยวข้อง', 'สำหรับคำถามเพิ่มเติม', 'คุณอาจถาม' ฯลฯ\n"
        "- ห้ามลงท้ายด้วยประโยคปิด เช่น 'หวังว่าจะเป็นประโยชน์', 'หากมีข้อสงสัยเพิ่มเติม' ฯลฯ — จบคำตอบที่ข้อมูลสุดท้ายได้เลย\n"
        "- ตอบเฉพาะคำถามที่ถามเท่านั้น ไม่ต้องตอบคำถามอื่นที่ไม่ได้ถาม\n"
        "- หากไม่พบคำตอบใน Context ให้ตอบว่า 'ขออภัย ไม่มีข้อมูลในส่วนนี้ กรุณาติดต่อ HR โดยตรงค่ะ'\n"
        "ตอบกระชับ ชัดเจน และเป็นมิตร"
    ),
    "en": (
        "You are Salary Hero's AI assistant for HR and payroll questions.\n"
        "Rules:\n"
        "- Use ONLY information explicitly present in the Context below.\n"
        "- Do NOT add, infer, or invent any details not found in the Context.\n"
        "- Do NOT start your answer with 'Based on the context', 'According to the context', or any similar phrasing — answer directly.\n"
        "- Do NOT add any follow-up question sections at the end — no 'Related questions', 'You might also ask', 'For more questions', etc.\n"
        "- Do NOT add a closing sentence like 'I hope this helps' or 'Feel free to ask' — end at the last piece of information.\n"
        "- Answer only the question asked — nothing more.\n"
        "- If the answer is not in the Context, say: 'Sorry, I don't have that information. Please contact HR directly.'\n"
        "Be concise, clear, and friendly."
    ),
}

FALLBACK_MESSAGE = {
    "th": "ขออภัย ไม่พบข้อมูลที่เกี่ยวข้อง กรุณาติดต่อฝ่าย HR โดยตรงค่ะ",
    "en": "Sorry, I couldn't find relevant information. Please contact HR directly.",
}


@dataclass
class GeneratedAnswer:
    text: str
    grounding_score: float          # 0.0 – 1.0
    was_escalated: bool = False
    handoff_context: Optional[dict] = None
    route_taken: str = ""


def generate_answer(
    message: str,
    context: str,
    language: str,
    tenant_id: str,
    intent: str,
    history: list[dict],
    route: str,
    system_prompt_override: str = "",
    top_retrieval_score: float = 0.0,
    prefilled_answer: str = "",
) -> GeneratedAnswer:
    """Generate a grounded answer and optionally escalate."""
    lang = language if language in ("th", "en") else "th"

    # Template answer — skip LLM entirely, return as-is
    if prefilled_answer:
        return GeneratedAnswer(
            text=prefilled_answer,
            grounding_score=1.0,
            was_escalated=False,
            route_taken=route,
        )

    if not context:
        return GeneratedAnswer(
            text=FALLBACK_MESSAGE[lang],
            grounding_score=0.0,
            was_escalated=True,
            route_taken=route,
        )

    user_prompt = (
        f"Context:\n{context}\n\n"
        f"Question: {message}"
    )

    system = system_prompt_override or SYSTEM_PROMPT[lang]
    messages = list(history) + [{"role": "user", "content": user_prompt}]
    answer = call_llm(messages=messages, system=system, language=lang)
    answer = _clean_answer(answer)

    score = _score_grounding(answer, context)
    # Troubleshooting context is generated by our own agent — always trustworthy.
    # High retrieval score (≥ 0.6) means the vector search found a strong match —
    # trust the answer even if Thai polite particles reduce word-overlap score.
    high_retrieval = top_retrieval_score >= 0.6
    escalate = (
        score < HANDOFF_THRESHOLD
        and not high_retrieval
        and "TROUBLESHOOTING" not in route.upper()
    )

    return GeneratedAnswer(
        text=answer if not escalate else FALLBACK_MESSAGE[lang],
        grounding_score=score,
        was_escalated=escalate,
        handoff_context={"original_message": message, "context": context} if escalate else None,
        route_taken=route,
    )


_PREAMBLE_RE = re.compile(
    # Thai: strip only when preamble ends with , : or newline within 30 chars
    # e.g. "จากข้อมูลที่ให้มา," / "ตามข้อมูลที่ระบุ," / "จากข้อมูลใน Context:"
    # NOT "ตามข้อมูลที่ระบุ กรณี..." (no separator = actual content, don't strip)
    r"^(จาก|ตาม)(ข้อมูล|บริบท)[^\n:,،]{0,40}[:\n,،]\s*"
    r"|^(based on|according to)\s+the\s+(provided\s+)?context[^\n:,]{0,30}[:\n,]\s*",
    re.IGNORECASE,
)


_RELATED_RE = re.compile(
    # Thai follow-up sections — various phrasings the LLM uses
    r"\n*\**สำหรับคำถามเพิ่มเติม[^\n]*:?.*$"
    r"|\n*\**(เกี่ยวกับ)?คำถามที่(เกี่ยวข้อง|อาจถาม|คุณอาจถาม)\**[^\n]*:?.*$"
    r"|\n*\**คุณอาจถาม[^\n]*:?.*$"
    # English follow-up sections
    r"|\n*(related questions?|you might also ask|for (more|additional) questions?)[^\n]*:?.*$",
    re.IGNORECASE | re.DOTALL,
)

_CLOSING_RE = re.compile(
    # Thai closing phrases
    r"\n*หวังว่า[^\n]*$"
    r"|\n*หากมี[^\n]*(สงสัย|ข้อสอบถาม|คำถาม)[^\n]*$"
    r"|\n*หากยังมี[^\n]*$"
    # English closing phrases
    r"|\n*(i hope this (helps|clarifies)|feel free to (ask|contact)|if you have (any )?(more|further|additional))[^\n]*$",
    re.IGNORECASE,
)


def _clean_answer(answer: str) -> str:
    """Strip preamble, follow-up question sections, and closing phrases the LLM adds."""
    answer = _PREAMBLE_RE.sub("", answer).lstrip()
    answer = _RELATED_RE.sub("", answer)
    answer = _CLOSING_RE.sub("", answer)
    return answer.rstrip()


def _score_grounding(answer: str, context: str) -> float:
    """
    Score how well the answer is grounded in the context.
    Uses word overlap as a lightweight heuristic.
    """
    if not context or not answer:
        return 0.0

    # Extract meaningful words (length > 2) from context and answer
    context_words = set(re.findall(r"\w{3,}", context.lower()))
    answer_words = set(re.findall(r"\w{3,}", answer.lower()))

    if not answer_words:
        return 0.0

    overlap = answer_words & context_words
    return min(len(overlap) / max(len(answer_words), 1), 1.0)
